# Generated by Django 2.2.12 on 2020-05-20 01:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200517_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
